# LANG:
#   METRIC_NAME:
#     model_name: str
#     model_revision: str (optional)
#     tokenizer_name: str (optional)
#     tokenizer_revision: str (optional)
#     loader_func: str
zh:
  semantic_similarity:
    model_name: BAAI/bge-base-zh-v1.5
    model_revision: f03589c
    loader_func: load_sentence_transformers

  sentiment:
    model_name: IDEA-CCNL/Erlangshen-Roberta-110M-Sentiment
    loader_func: load_auto_model_for_text_classification

  toxicity:
    model_name: alibaba-pai/pai-bert-base-zh-llm-risk-detection
    model_revision: 0a61c79744cb0173216f015ffecc1ea81c4e0229
    loader_func: load_auto_model_for_text_classification

  factual_consistency:
    model_name: Helsinki-NLP/opus-mt-zh-en
    model_revision: cf109095479db38d6df799875e34039d4938aaa6
    loader_func: load_auto_model_for_seq2seq

en:
  fluency:
    model_name: prithivida/parrot_fluency_model
    model_revision: e5224ff5b4109cd949ce25b0a6dff8d8cbdec7be
    loader_func: load_auto_model_for_text_classification

ja:
  fluency:
    model_name: liwii/fluency-score-classification-ja
    model_revision: c3733331b98075eeb25234ea816a2243843aa72f
    tokenizer_name: line-corporation/line-distilbert-base-japanese
    tokenizer_revision: 93bd4811608eecb95ffaaba957646efd9a909cc8
    loader_func: load_auto_model_for_text_classification

  sentiment:
    model_name: cardiffnlp/twitter-xlm-roberta-base-sentiment-multilingual
    model_revision: 4bbfd0204cabf80eb8081058bf838c1e6ef70a69
    loader_func: load_auto_model_for_text_classification

  toxicity:
    model_name: Alnusjaponica/toxicity-score-multi-classification
    model_revision: f05dea2ed024b186a15fa2d0c56bbd65fbc60dba
    tokenizer_name: line-corporation/line-distilbert-base-japanese
    tokenizer_revision: 93bd4811608eecb95ffaaba957646efd9a909cc8
    loader_func: load_auto_model_for_text_classification
