name: Python Code Format Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on pull request events
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "format"
  format:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out this repository so this job can access it
      - uses: actions/checkout@v2

      # Use Python 3.8.16
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8.16'

      # Install the langcheck package with dev dependencies
      - run: |
          pip install --upgrade pip
          pip install .[dev]

      # Run the yapf format test
      - run: yapf --diff -r .

      # Run the flake8 format test
      - run: flake8 .

      # Run the isort format test
      - run: isort --check-only .
